name: Cache

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
          - build: windows
            os: windows-latest
            rust: stable-x86_64-msvc
            target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v4
    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: npm
    - name: Build web
      shell: bash
      run: npm install
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: "src-api"
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
    - name: Build
      run: cd src-api && cargo build --verbose --release --target ${{ matrix.target }}
      env:
        RUST_BACKTRACE: 1
